sonar.projectKey=app-reservas
sonar.projectName=ReservasEC
sonar.projectVersion=1.0.0

sonar.sources=auth-service/src,booking-service/src,user-service,notification-service,frontend/src
sonar.tests=auth-service/__tests__,booking-service/__tests__,user-service/__tests__,notification-service/__tests__,frontend/src/__tests__
sonar.test.inclusions=**/*.test.js,**/*.test.ts,**/*.test.tsx

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/node_modules/**,**/coverage/**,**/__tests__/**,**/*.config.*,**/next.config.ts

sonar.exclusions=**/node_modules/**,**/coverage/**,**/.next/**,**/public/**
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300

sonar.sourceEncoding=UTF-8
sonar.language=js
sonar.javascript.maxFileSize=1000

sonar.verbose=false